
# Notes.
# Disable swap for kube, it really wants it dead
# https://askubuntu.com/questions/912623/how-to-permanently-disable-swap-file

- name: Install Kube commons
  hosts: kube-master
  become: true
  vars:
    pips:
      - openshift
      - pyyaml
    kubernetes_role: "master"
    kubernetes_allow_pods_on_master: true
    kubernetes_kubelet_extra_args: "--fail-swap-on=false"

  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes

  tasks:
    - name: pip req
      pip:
        state: present
        name: "{{ item }}"
      loop: "{{ pips }}"
