
- name: Install Kube commons
  hosts: kube-node
  become: true
  vars:
    pips:
      - openshift
      - pyyaml
    kubernetes_role: "node"
    kubernetes_kubelet_extra_args: "--fail-swap-on=false"
    kubernetes_join_command: 'kubeadm join 192.168.0.242:6443 --token 1ztncd.hzhxuvqepekrool2 --discovery-token-ca-cert-hash sha256:ae8851e8faaf9f76d5e68934f33332c43ef5c767c831ade49dabefab385b1fdc'

  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes


  tasks:  
    - name: pip req
      pip:
        state: present
        name: "{{ item }}"
      loop: "{{ pips }}"
