# Ansible Galaxy requirements file
# run 'ansible-galaxy install -r requirements.yml' to install what is defined in this file

roles:
  - src: geerlingguy.ansible
  - src: geerlingguy.awx
  - src: geerlingguy.docker
  - src: geerlingguy.git
  - src: geerlingguy.java
  #- src: geerlingguy.jenkins
  - src: geerlingguy.nodejs
  - src: geerlingguy.pip
  - src: jnv.unattended-upgrades
  - src: https://github.com/luther38/docker_volume_management
    name: luther38.docker_volume_management
    version: master

  - src: https://github.com/luther38/nagioscore
    name: luther38.nagioscore
    version: master

  - src: https://github.com/luther38/ansible_discord_webhook
    name: luther38.discord_webhook
    version: master

#collections:
