
# Notes.
# Disable swap for kube, it really wants it dead
# https://askubuntu.com/questions/912623/how-to-permanently-disable-swap-file

# The difference between the master and node is defined in the inventory.

- name: Install Kubernetes
  hosts: kube
  become: true
  vars:    
    kubernetes_allow_pods_on_master: false
    kubernetes_kubelet_extra_args: "--fail-swap-on=false"
    kubernetes_enable_web_ui: true
    kubernetes_web_ui_manifest_file: https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

  tasks:
    #- include_role:
    #    name: geerlingguy.docker

    - name: Disable swap
      shell: swapoff -a

    - include_role:
        name: geerlingguy.kubernetes     

    - name: Mount kube nfs share
      mount:
        src: "{{ kube_fs_ip }}:{{ kube_fs_mount }}"
        path: "{{ kube_fs_mount }}"
        fstype: nfs
        boot: yes
        state: mounted
      ignore_errors: true

    - name: Mount kube backups nfs share
      mount:
        src: "192.168.1.85:/kube/"
        path: "/mnt/kube/backup"
        fstype: nfs
        boot: yes
        state: mounted
      ignore_errors: true