---

# cmd - kubectl apply -f deploy.yml
#

apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: minecraft
  name: minecraft
  namespace: default
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"