---

- name: testing backup plan
  hosts: localhost
  vars:
    containers:
      - hydra

  tasks:
    

    - name: looping though containers
      block:
        - name: Get container data
          docker_container_info:
            name: "{{ item }}"
          register: output

        - debug:
            msg: "{{ output.container.Name }}"

        - name: stop container for backups
          docker_container:
            name: "{{ item }}"
            state: stopped
        
        - name: thing
          debug:
            #msg: "{{ item }}"
            msg: "~/docker/backup{{ output.container.Name }}{{ item.Destination }}"
          loop: "{{ output.container.Mounts }}"
          #when: item.Type == 'bind'

        - name: Confirm ~/docker/backup{{ output.container.Name }} exists
          file:
            path: "~/docker/backup{{ output.container.Name }}"
            state: directory

        - name: Backup {{ item.Destination }}
          archive:
            path: "{{ item.Source }}"
            dest: "~/docker/backup{{ output.container.Name }}{{ item.Destination }}.gz"
          loop: "{{ output.container.Mounts }}"
          when: item.Type == 'bind'
      loop: "{{ containers }}"
      