---
- name: testing backup plan
  hosts: mediaserver-back
  become: true
  vars:
    dvb_path_backup:    '/docker/nfs/backup'
    dvb_backup_volume:  '/config'
    discord_webhook: "{{ discord_mm_hook }}"
    discord_name: 'Ansible Monitor - Backend'

  tasks:
    - include_role:
        name: ansible_discord_webhook
      vars:
        discord_message: "Backup Job:\nJob is starting.  Services will be going offline and brought back up once the service has finished."

    - set_fact:
        dvb_container_name: 'hydra'
    - include_role:
        name: ansible-role-docker-volume-backup
    
    - set_fact:
        dvb_container_name: 'nzbget'
    - include_role:
        name: ansible-role-docker-volume-backup
          
    - set_fact:
        dvb_container_name: 'sonarr'
    - include_role: 
        name: ansible-role-docker-volume-backup

    - set_fact:
        dvb_container_name: 'radarr'
    - include_role:
        name: ansible-role-docker-volume-backup

    - include_role:
        name: ansible_discord_webhook
      vars:
        discord_message: "Backup Job:\nJob has finished and services should be back online."
