---
- name: testing backup plan
  hosts: mediaserver-back
  become: true
  vars:
    backup: false
  tasks:
    - name: Ensure backup location is present
      file:
        path: /tmp/docker/backup
        state: directory

    - name: Backup Search
      block:
        - name: Check on old backups
          find:
            path: "{{ pathNfsBackup }}/hydra"
            age: 4w
          register: searchRes

        - name: Remove old backups
          file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ searchRes.files }}"

        - name: stop search
          docker_container:
            name: mediaback_search_1
            state: stopped

        - name: generate archive
          community.general.archive:
            path: /docker/cfg/hydra
            dest: "{{ pathNfsBackup }}/hydra/backup.tgz"

        - name: start search
          docker_container:
            name: mediaback_search_1
            state: started
      when: backup == true

    - name: Backup son
      block:
        - name: Check on old backups
          find:
            path: "{{ pathNfsBackup }}/sonarr"
            age: 4w
          register: searchRes

        - name: Remove old backups
          file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ searchRes.files }}"

        - name: stop son
          docker_container:
            name: mediaback_son_1
            state: stopped

        - name: generate archive
          community.general.archive:
            path: /docker/cfg/sonarr
            dest: "{{ pathNfsBackup }}/sonarr/backup.tgz"

        - name: start son
          docker_container:
            name: mediaback_son_1
            state: started
      when: backup == true

    - name: Backup rad
      block:
        - name: Check on old backups
          find:
            path: "{{ pathNfsBackup }}/radarr"
            age: 4w
          register: searchRes

        - name: Remove old backups
          file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ searchRes.files }}"

        - name: stop rad
          docker_container:
            name: mediaback_rad_1
            state: stopped

        - name: generate archive
          community.general.archive:
            path: /docker/cfg/radarr
            dest: "{{ pathNfsBackup }}/radarr/backup.tgz"

        - name: start rad
          docker_container:
            name: mediaback_rad_1
            state: started
      when: backup == true

    - name: Backup get
      block:
        - name: ensure backup dir is present
          file:
            path: "{{ pathNfsBackup }}/mediback_get_1"
            state: directory

        - name: Check on old backups
          find:
            path: "{{ pathNfsBackup }}/mediaback_get_1"
            age: 4w
          register: searchRes

        - name: Remove old backups
          file:
            path: "{{ item.path }}"
            state: absent
          loop: "{{ searchRes.files }}"

        - name: stop get
          docker_container:
            name: mediaback_get_1
            state: stopped
            
        - name: generate archive
          community.general.archive:
            path: /docker/cfg/nzbget
            dest: "{{ pathNfsBackup }}/mediaback_get_1/backup.tgz"

        - name: start get
          docker_container:
            name: mediaback_get_1
            state: started