---
- name: testing backup plan
  hosts: mediaserver-back
  become: true
  vars:
    dvb_PathBackup:     '/docker/nfs/backup'
    dvb_backup_volume:  '/config'

  tasks:

#    - include_role:
#        name: ansible_discord_webhook
#      vars:
#        discord_webhook: "{{ discord_test_hook }}"
#        discord_username: 'Ansible Monitor'
#        discord_message: "Backend services are going offline for backup jobs to run."

    - set_fact:
        dvb_container_name: 'sonarr'

    - include_role: 
        name: ansible-role-docker-volume-backup

#    - include_role:
#        name: docker_volume_management
#      vars:
#        container_name: 'hydra'

#    - include_tasks: task-backup.yml
#      vars:
#        container: "hydra"
#        #pathBackup: '~/docker/backup'
    
#    - include_tasks: task-backup.yml
#      vars:
#        container: "nzbget"
#        #pathBackup: 

#    - include_tasks: task-backup.yml
#      vars:
#        container: "sonarr"
#        ok_mount: '/config' 
          
#    - include_tasks: task-backup.yml
#      vars:
#        container: "radarr"
      