---

- name: Maintain and Configure Cron jobs
  hosts: mediaserver-back
  become: true
  vars:
    aptPackages:
      - git

    pipPackages:
      - ansible

  tasks:
    - name: Install Required packages
      apt: 
        name: git
        state: present

    - name: Install Ansible
      pip:
        name: ansible
        state: present
    
#    - name: Make working dir
#      file:
#        path: /usr/ansible
#        state: directory

    - name: Configure Ansible Repo
      git:
        repo: 'https://github.com/luther38/ansible.git'
        dest: /usr/ansible

    - name: Install Requirements.yml
      shell: cd /usr/ansible && ansible-galaxy install -r requirements.yml --force

    - name: Make Cron log location
      file:
        state: directory
        path: /tmp/ansible/log/

    # Add vault pass

    - name: Cron - pull down newest dev branch
      cron: 
        name: Update ansible repo
        state: present
        job: cd /usr/ansible && git checkout dev && git pull > /tmp/ansible/log/pull.log
        minute: "0"
        hour: "*"
        day: "*"

    - name: Cron - Update roles
      cron: 
        name: Update Ansible Roles
        state: present
        job: cd /usr/ansible && ansible-galaxy install -r requirements.yml > /tmp/ansible/logs/galaxy.log
        minute: "1"
        hour: "*"
        day: "*"

    - name: Cron - Make sure cron is up to date
      cron:
        name: Update crontabs
        state: present
        job: cd /usr/ansible && ansible-playbook ./playbook/docker/mediaserver/back/cron.yml > /tmp/ansible/log/cron.log
        minute: "1"
        hour: "*"
        day: "*"

    #- name: Cron - Run Linux Common

    - name: Cron - Discord Test
      cron:
        name: Discord Test
        state: present
        job: cd /usr/ansible && /usr/local/bin/ansible-playbook ./playbook/localhost/discord_test.yml
        minute: "1"

    # Restart Containers

    # Backup Containers

    # Update Containers on Saturday