
---

- name: enable 
  hosts: linux

  tasks:
        - name: unattended-upgrades
          become: true
          include_role:
                  name: jnv.unattended-upgrades
          vars:
                  #unattended_package_blacklist: []
                  unattended_automatic_reboot: true


