---
# This is a common playbooks for all linux servers
# Contains all the basics needed for servers to get started
# Once this is installed and maintained look for server based roles like docker servers 

- name: Install Linux Requirement
  hosts: linux-all
  become: yes

  tasks:
    - include_role:
        name: common
      vars:
        linux: true