---
# This is a common playbooks for all linux servers
# Contains all the basics needed for servers to get started
# Once this is installed and maintained look for server based roles like docker servers 

- name: Install Linux Requirement
  hosts: linux-all
  become: yes

  tasks:
    - name: install packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python3
          - python3-pip
          - nfs-common
          - tree
      when: ansible_distribution == "Ubuntu"

    - name: Install pip
      include_role:
        name: geerlingguy.pip

    # https://galaxy.ansible.com/jnv/unattended-upgrades
    - name: unattended-upgrades
      become: true
      include_role:
        name: jnv.unattended-upgrades
      vars:
        #unattended_package_blacklist: []
        unattended_automatic_reboot: true

    - name: Install VMware tools if valid
      include_role:
        name: ruzickap.vmwaretools
      when: ansible_virtualization_type == 'VMware'
