
---

- name: install Jenkins
  hosts: jenkins
  become: true
  vars:
    jenkins_package_state: latest
    jenkins_http_port: 8080

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.docker

  tasks:
    - name: Give jenkins docker group
      shell: usermod -a -G docker jenkins
      
    - name: Backup Jenkins Jobs
      become: yes
      fetch:
        src: /var/lib/jenkins/jobs/
        dest: ./jenkins/jobs/

    - name: UFW Allow Jenkins
      ufw:
        rule: allow
        port: 8080
        comment: Jenkins

