
---

- name: install Jenkins
  hosts: jenkins

  tasks:
        - name: Install Java
          become: yes
          import_role:
                name: geerlingguy.java

        - name: Install Jenkins
          become: yes
          import_role:
                  name: geerlingguy.jenkins
          vars:
                  jenkins_package_state: latest
                  jenkins_http_port: 8080

        - name: UFW Allow Jenkins
          become: yes
          ufw:
                rule: allow
                port: 8080
                comment: Jenkins

