
---

- name: install Jenkins
  hosts: jenkins
  become: true
  vars:
    jenkins_package_state: latest
    jenkins_http_port: 8080

    # nginx
    revproxy_metal_install: true
    revproxy_01_location: '/'
    revproxy_01_server: 'http://localhost:8080/'

  roles:
   # - luther38.revproxy
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.docker

  tasks:
    - user:
        name: jenkins
        shell: /bin/bash
        groups: docker

    #- name: Give jenkins docker group
    #  shell: usermod -a -G docker jenkins

    - name: Install Ansible
      apt:
        name: ansible
        state: present
      
    - name: Backup Jenkins Jobs
      become: yes
      archive:
        path: /var/lib/jenkins/jobs/
        dest: /tmp/jenkinsjobs.zip
        format: zip

    - name: UFW Allow Jenkins
      ufw:
        rule: allow
        port: 8080
        comment: Jenkins

