---

- name: Enable passwordless access via ssh
  hosts: kube
  become: true
  vars:
    users: 
      - name: ansible

  tasks:
    - name: Checking for users
      user:
        name: ansible
        groups: admin

    - name: Copy 

    - debug:
        msg: "{{ existingUsers }}"
