
- name: Update Repos
  hosts: linux

  tasks:
    - name: Update Repos
      become: true
      become_method: sudo
      apt:
        update_cache: yes

    - name: Upgrade Packages
      become: true
      become_method: sudo
      apt:
        upgrade: yes

    - name: Remove unused packages
      become: true
      become_method: sudo
      apt:
        autoremove: yes