---
# tasks/SmartOS/rabbit.yml: Deploy RabbitMQ
# Specific to Joyent SmartOS

- name: Ensure RabbitMQ is installed
  tags: rabbitmq
  pkgin: name=rabbitmq state=present

- name: Ensure EPMD is running
  tags: rabbitmq
  service:
    name: epmd
    state: started
    enabled: true
