---

- name: install awx
  hosts: awx
  become: true
  vars:
    #nodejs_version: "6.x"
    pip_install_packages:
      - name: docker

  roles:
    #- geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx
