---

- name: generate PiHole Server
  hosts: pihole
  become: true
  vars:
    pathDocker: "/docker"
    pathConfig: "{{ pathDocker }}/config"
    pathLocalPihole: "{{ pathDocker}}/pihole/"
    pathDnsmasq: "{{ pathDocker }}/dnsmasq/"

    nfsAddress: 192.168.0.16
    nfsDockerConfig: "docker"

  tasks: 
    - name: Install docker
      import_role:
        name: geerlingguy.docker

    - name: make docker folder
      file:
        path: "{{ pathDocker }}"
        state: directory

    - name: make config folder
      file:
        path: "{{ pathConfig }}"
        state: directory

    - name: make dnsmasq folder
      file:
        path: "{{ pathLocalPihole }}"
        state: directory

    - name: make dnsmasq folder
      file:
        path: "{{ pathDnsmasq }}"
        state: directory

    - name: mount nfs to /docker/config
      mount:
        src: "{{ nfsAddress }}:/{{ nfsDockerConfig }}"
        path: "{{ pathConfig }}"
        fstype: nfs
        boot: yes
        state: mounted

    - name: Stop PiHole
      docker_container:
        name: pihole
        state: stopped
      ignore_errors: yes

    - name: Get the Docker image
      docker_image:
        name: pihole/pihole
        #source: pull
        tag: latest

    - name: Start PiHole
      docker_container:
        name: piholemk1
        image: 'pihole/pihole'
        state: started
        network_mode: host
        env:
          TZ=America/Chicago
          DNS1="1.1.1.1"
          DNS2="1.0.0.1"
          WEBPASSWORD="admin"
          ServerIP="{{ ansible_host }}"
          WEB_PORT="8080"
        volumes:
          - "{{ pathLocalPihole }}:/etc/pihole/"
          - "{{ pathDnsmasq }}:/etc/dnsmasq.d/"
