---

- name: generate PiHole Server
  hosts: pihole
  become: true
  vars:
    pathDocker: "/docker"
    pathPiHole: "{{ pathDocker }}/pihole"

    nfsAddress: 192.168.0.16
    nfsDockerConfig: "docker"

  tasks: 
    - name: Install docker
      import_role:
        name: geerlingguy.docker

    - name: make docker folder
      file:
        path: "{{ pathDocker }}"
        state: directory

    - name: make pihole folder
      file:
        path: "{{ pathPiHole }}"
        state: directory

    - name: mount nfs to /docker/config
      mount:
        src: "{{ nfsAddress }}:/{{ nfsDockerConfig }}"
        path: "{{ pathConfig }}"
        fstype: nfs
        boot: yes
        state: mounted

    - name: Start PiHole
      docker_container:
        name: pihole
        image: 'pihole/pihole:latest'
        state: started
        ports:
          - 53:53/tcp
          - 53:53/udp
          - 67:67/udp
          - 80:80/tcp
          - 443:443/tcp
        environment:
          TZ: 'America/Chicago'
          # WEBPASSWORD: 'set a secure password here or it will be random'    
        volumes:
          - "{{ pathPiHole }}/pihole/config:/etc/pihole/"
          - "{{ pathPiHole }}/pihole/dnsmasq:/etc/dnsmasq.d/"
        dns:
          - 127.0.0.1
          - 1.1.1.1


