---

- name: Ensure InfluxDB is active
  hosts: localhost
  vars:
    images:
      - influxdb
      - telegraf
      - chronograf

  tasks:
    - name: install influxdb
      package:
        name: "{{ item }}"
        state: absent
      loop: "{{ images }}"