---

- name: Install MacOS Dev Tools
  hosts: localhost
  vars:
    brew_packs:
      - python3
      - pipenv
      - golang
      - ranger
      - ansible
      - docker
    cask_packs:
      - visual-studio-code
      - vagrant
      - amethyst
      - docker

  tasks:
    - name: Install brew packages
      homebrew:
        name: "{{ brew_packs }}"
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Install cask packages
      homebrew_cask:
        name: "{{ cask_packs }}"
        state: present
      when: ansible_distribution == "MacOSX"

