---

- name: Install MacOS Dev Tools
  hosts: osx

  tasks:
    - name: Install python3 dev
      homebrew:
        name: python3
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Install pipenv
      homebrew:
        name: pipenv
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Install VisualStudioCode
      homebrew_cask:
        name: visual-studio-code
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Install vagrant
      homebrew_cask:
        name: vagrant
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Install amethyst
      homebrew_cask:
        name: amethyst
        state: present
      when: ansible_distribution == "MacOSX"

    - name: Install docker
      homebrew_cask:
        name: docker
        state: present
      when: ansible_distribution == "MacOSX"

    - name: remove cask - darktable
      homebrew_cask:
        name: darktable
        state: absent
      when: ansible_distribution == 'MacOSX'

    #TODO The job seems to stop here for some reason
    - name: remove cask - dotnet-sdk
      become: true
      homebrew_cask:
        name: dotnet-sdk
        state: absent
      when: ansible_distribution == 'MacOSX'

    - name: remove cask - visual-studio
      homebrew_cask:
        name: visual-studio
        state: absent
      when: ansible_distribution == 'MacOSX'

    - name: remove cask - rider
      homebrew_cask:
        name: rider
        state: absent
      when: ansible_distribution == 'MacOSX'


