---

- name: deploy plex
  hosts: mediaserver-front
  become: true
  vars:
    pathDockerRoot: "/docker"
    pathConfig:     "{{ pathDockerRoot }}/cfg"
    pathMedia:      "/docker/nfs/media"    
    update: false
 
  tasks:
    #- name: Maintain Defaults
    #  include_role:
    #    name: common
    #  vars:
    #    mediaserver: true
    #    plex: true

    - name: Stop Plex
      docker_container:
        name: plex
        state: stopped
      ignore_errors: yes

    - name: update image
      shell: docker pull linuxserver/plex
      when: update == true

    - name: remove old container
      shell: docker container rm plex
      ignore_errors: true

    - name: Start Plex
      docker_container:
        name: plex
        image: linuxserver/plex:1.18.2.2058-e67a4e892-ls70
        state: started
        network_mode: host
        restart_policy: unless-stopped
        env:
          PUID=0
          PGID=0
          TZ="{{ ntp_timezone }}"
          UMASK_SET=022
        volumes:
          - "{{ pathConfig }}/plex:/config"
          - "{{ pathMedia }}:/tv"

    #- name: remove old image
    #  shell: docker image prune --force