
- name: Check for updates
  hosts: windows

  tasks:
    - name: Check for updates.  Log the needed updates.
      win_updates:
        state: searched
        category_name:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
      register: output
    
    - debug: msg="{{ output }}"


