

- name: Check on Syncthing container
  docker_container:
    name: syncthing
  register: status

- name: Stop Synthing
  docker_container:
    name: syncthing
    status: stopped

- name: Pull Image
  docker_image:
    name: 'linuxserver/syncthing'
    source: pull

- name: Deploy Syncthing
  docker_container:
    name: syncthing
    image: 'linuxserver/syncthing'
    state: started
    restart_policy: unless-stopped
    env:
      PUID="{{ PUID }}"
      PGID="{{ PUID }}"
      TZ="{{ EnvTimeZone }}"
    ports:
      - "{{ 8384 }}:8384"
      - "{{ port22000 }}:22000"
      - "{{ port21027 }}:21027/udp"
    volumes:
      - "{{ pathConfig }}:/config"
      - "{{ pathData }}:/data1"
