
# - name: enable modules
- name: enable system module
  become: true
  shell: metricbeat modules enable system

  #- name: start metricbeat service
  #  become: true
  #shell: metricbeat service metricbeat start

- name: systemd - daemon reload
  become: true
  systemd:
        daemon_reload: yes

- name: Enable service on system startup
  become: true
  systemd:
        name: metricbeat
        enabled: yes

- name: systemd - restart Metricbeat
  become: true
  systemd:
        name: metricbeat
        state: restarted
