
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service

apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565