---
# tasks file for luther38.metricbeat

- name: Install Metricbeat on Ubuntu
  when: ansible_distribution == 'Ubuntu'
  include: ubuntu.yml

- name: Install Metricbeat on Windows
  when: ansible_distribution == 'Windows'
  include: windows.yml
