- name: install packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - nfs-common

- name: install pip packages
  pip:
    name: "{{ pipPacks }}"
    state: present
  vars:
    pipPacks:
      - docker
  
- name: install docker
  include_role:
    name: geerlingguy.docker

- name: make /docker folder
  file:
    path: "/docker"
    state: directory
