---

- name: make docker folder location
  file:
    path: "{{ pathDockerRoot }}"
    state: directory

- name: make docker config folder
  file:
    path: "{{ pathConfig }}"
    state: directory

- name: make download folder
  file:
    path: "{{ pathDownloads }}"
    state: directory

- name: make media folder
  file:
    path: "{{ pathMedia }}"
    state: directory
  when: plex == True

- name: mount nfs to /docker/config
  mount:
    src: "{{ nfsAddress }}:/{{ nfsDockerConfig }}"
    path: "{{ pathConfig }}"
    fstype: nfs
    boot: yes
    state: unmounted

- name: mount nfs to /docker/plex
  mount:
    src: "{{ nfsAddress }}:/{{ nfsMedia }}"
    path: "{{ pathMedia }}"
    fstype: nfs
    boot: yes
    state: mounted
  when: plex == True

- name: install docker pip package
  pip:
    name: docker
    state: present
    executable: pip3

- name: make docker network
  docker_network:
    name: "{{ dockerNetwork }}"
