
- name: Allow 5601 though UFW
  become: true
  ufw:
          rule: allow
          port: 5601

- name: systemd - daemon reload
  become: true
  systemd:
          daemon_reload: yes

- name: systemd - enable Kibana on startup
  become: true
  systemd:
          name: kibana
          enabled: yes

- name: systemd - restart Kibana 
  become: true
  systemd:
          name: kiband
