---

- name: systemd - daemon reload
  become: true
  systemd:
        daemon_reload: yes

- name: system - enable on startup
  become: true
  systemd:
        name: heartbeat-elastic
        enabled: yes

- name: systemd - restart heartbeat
  become: true
  systemd:
        name: heartbeat-elastic
        state: restarted
