# This will work on a new install.

# Allow 9200 so we can access it over the network
- name: Allow port 9200 though UFW
  become: true
  ufw:
          rule: allow
          port: 9200
          #name: ElasticSearch

- name: Allow port 9300 though UFW
  become: true
  ufw:
          rule: allow
          port: 9300

- name: Service reload daemon
  become: true
  systemd:
          daemon_reload: yes

- name: systemd - enable ElasticSearch on startup
  become: true
  systemd:
          name: elasticsearch
          enabled: yes

- name: systemd - restart ElasticSearch service
  become: true
  systemd:
          name: elasticsearch
          state: restarted
