

---

- name: Install Metricbeat
  hosts: elasticClients

  tasks:
          - name: Install Metricbeat
            become: true
            include_role:
                    name: luther38.metricbeat
            vars:
                    kibana_host: 172.20.0.142
                    elasticsearch_hosts: '["172.20.0.142:9200"]' 
                    systemd_enable_service: true
                    systemd_restart_service: true

