---
# This will install all the client parts needed for elastic to monitor client computers

- name: Install elastic client programs
  hosts: elasticClients
  vars:
          kibana_host: '192.168.0.173:5601'
          elasticsearch_hosts: '["192.168.0.173:9200"]'

  tasks:
        - name: Install elastic repo
          include: install-repo.yml

        - name: Install elastic heartbeat
          become: true
          apt:
          name: heartbeat-elastic

        - name: Update Heatbeat config
          become: true
          template:
                  src: heartbeat.j2
                  dest: /etc/heartbeat/heartbeat.yml
        
        - name: Configure elastic heartbeat
          include: config-heartbeat.yml

        - name: Install elastic metricbeat
          become: true
          apt:
                name: metricbeat

        - name: Update Metricbeat config
          become: true
          template:
                  src: metricbeat.j2
                  dest: /etc/metricbeat/metricbeat.yml

        - name: Configure elastic metricbeat
          include: config-metricbeat.yml
