

- name: Install Elasticsearch
  hosts: elastic

  tasks:
        - name: Install Elastic GPG Key
          become: true
          apt_key:
                url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
                state: present
                id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
        
        - name: Install apt-transport-https
          apt:
                name: apt-transport-https
        - name: Add Elastic Repo
          become: true
          copy:
                src: elastic-7.x.list
                dest: /etc/apt/sources.list.d/
                backup: yes

        - name: Update Packages
          become: true
          apt:
                update_cache: true

        - name: Install ElasticSearch
          become: true
          apt:
                name: elasticsearch

        - name: Allow port 9200 though UFW
          become: true
          ufw:
                rule: allow
                port: 9200
                #name: ElasticSearch

        - name: Service reload daemon
          become: true
          systemd:
                daemon_reload: yes

        - name: Start ElasticSearch
          become: true
          systemd:
                name: elasticsearch
                enabled: yes


