---
# This will install all elastic services for a elastic server
# ElasticSearch
# Kibana

- name: Install Elastic server programs
  hosts: elastic
  vars:
          cluster_name: 'logging-dev'
          node_name: 'dev-data-01'
          node_master: 'true'
          node_data: 'true'
          path_data: '/var/lib/elasticsearch'
          path_logs: '/var/log/elasticsearch'
          network_host: {{ ansible_default_ipv4.address }}
          http_port: '9200'
          transport_host: 'localhost'
          transport_port: '9300'

  tasks:
        - name: Install Requrements
          include: install-repo.yml

        - name: Install ElasticSearch from apt
          become: true
          apt:
                name: elasticsearch

        - name: Configure ElasticSearch
          include: config-elasticsearch.yml

        - name: Install Kibana from apt
          become: true
          apt: 
                name: kibana

        - name: Configure Kibana
          include: config-kibana.yml
