
- name: testing elastic role
  hosts: elastic

  tasks:
        - name: test role
          import_role: 
                name: elasticsearch
          vars:
                cluster_name: "loggin-dev"
                ufw_http_port: true
                ufw_transport_port: true
                systemd_enabled: true
                systemd_restart: true

        - name: install kibana
          import_role:
                name: kibana
          vars:
                server_port: 5601
                server_host: ansible_default_ipv4.address
                server_name: ansible_hostname
                elasticsearch_hosts:
                        - http://192.168.0.173:9200

