---
- name: Debug Okta Groups
  hosts: localhost
  vars_files: okta_vars.yml

  tasks:
    - name: Get Okta Group
      okta_groups:
        organization: "{{ org }}"
        api_key: "{{ api }}"
        action: list
        limit: 200
      register: res

    - name: show res
      debug:
        msg: "{{ item.profile.name }} {{ item.id }}"
      loop: "{{ res.json }}"
