---
# Inventory vars for the 'kube-fs' host
monit_filesystems:
  - name: root
    path: /
    when:
    - usage: '> 80%'
      tries: 1
      cycles: 1
      alert: false
      exec: "{{ monit_discord_alert_script }}"

  - name: 'mnt/data'
    path: '/mnt/data'
    when:
    - usage: '> 80%'
      tries: 1
      cycles: 1
      alert: false
      exec: "{{ monit_discord_alert_script }}"


