---

- name: Backup container volumes
  hosts: mediaserver-front
  become: true
  vars:
    name: plex

  tasks:
    - name: "{{ name }} - stop"
      shell: docker container stop {{ name }}
      ignore_errors: true

    - import_role:
        name: docker_volume_management
      vars:
        role_action: backup
        container_name: "{{ name }}"
        mount_point: '/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/'
        backup_folder: /docker/backup
        tar_file: "{{ name }}Config.tar"

    #- name: hydra Backup 
    #  shell: docker run --rm --volumes-from {{ name }} -v {{ backup_location }}:/backup ubuntu bash -c 'cd {{ mount_point }} && tar cvf /backup/{{ tar_file }} .'

    - name: Copy backup to external
      copy:
        src: /docker/backup/{{ name }}Config.tar
        dest: /docker/config/backup/
        remote_src: true

