---

- name: Backup container volumes
  hosts: mediaserver-back
  become: true
  vars:
    name: hydra
    mount_point: "/config"
    backup_location: /docker/backup
    tar_file: hydraConfig.tar

  tasks:
    - name: hydra - stop
      shell: docker container stop {{ name }}
      ignore_errors: true

    - import_role:
        name: luther38.docker_volume_management
      vars:
        action: backup
        container_name: hydra
        mount_point: '/config'
        backup_folder: /docker/backup
        tar_file: HydraConfig.tar

    #- name: hydra Backup 
    #  shell: docker run --rm --volumes-from {{ name }} -v {{ backup_location }}:/backup ubuntu bash -c 'cd {{ mount_point }} && tar cvf /backup/{{ tar_file }} .'

    #- name: Copy backup to external


      

