
- name: Configure Media Server
  hosts: mediaserver-back
  become: yes
  vars:
    update: false
    pathDockerRoot: "/docker"
    pathConfig:     "{{ pathDockerRoot }}/cfg"
    pathMedia:      "{{ pathDockerRoot }}/media"
    pathDownloads:  "{{ pathDockerRoot }}/downloads"
    nfsAddress:     192.168.0.16
    nfsDockerConfig: "docker"
    nfsMedia:       "plex"
    nfsMovies:      "plex"
    nfsTV:          "plex"
    dockerNetwork:  mediaserver
  
  tasks:
    - name: Run common docker
      include_role:
        name: common
      vars:
        medaiserver: true

    - name: stop hydra
      docker_container:
        name: hydra
        state: stopped
      ignore_errors: yes

    # Get version of container

    # Backup hydraConfig
    - name: hydra - backup config
      archive:
        path: "{{ pathConfig }}/hydra"
        dest: "/docker/backup/hydraconfig.gz"
        format: gz
        remove: false

    - name: hydra - update image
      shell: docker pull linuxserver/hydra2
      when: update == true

    - name: hydra - remove old container
      shell: docker container rm hydra
      ignore_errors: true

    - name: hydra - Make Hydra
      docker_container:
        name: hydra
        image: 'linuxserver/hydra2'
        state: started
        restart_policy: unless-stopped 
        env:
          PUID=0
          PGID=0
          TZ=Europe/London
        ports:
          - 5076:5076
        volumes:
          - "{{ pathConfig }}/hydra:/config"
          - "{{ pathDownloads }}:/downloads"
        networks:
          - name: "{{ dockerNetwork }}"
            ipv4_address: 172.18.0.10

    - name: sonarr - stop container
      docker_container:
        name: sonarr
        state: stopped
      ignore_errors: yes

    - name: sonarr - update image
      shell: docker pull linuxserver/hydra2
      when: update == true

    - name: sonarr - remove old container
      shell: docker container rm sonarr

    - name: sonarr- backup config 
      archive:
        path: "{{ pathConfig }}/sonarr"
        dest: /docker/backup/sonarrconfig.gz
        format: gz
        remove: false

    - name: sonarr - start 
      docker_container:
        name: sonarr
        image: linuxserver/sonarr:latest
        state: started
        restart_policy: unless-stopped 
        env:
          # Use 0 because this runs as root
          PUID=0
          PGID=0
          TZ=Europe/London
          UMASK_SET=022 #optional
        ports:
          - 8989:8989
        volumes:
          - "{{ pathConfig }}/sonarr:/config"
          - "{{ pathMedia }}:/tv"
          - "{{ pathDownloads }}:/downloads"
        networks:
          - name: "{{ dockerNetwork }}"
            ipv4_address: 172.18.0.11

    - name: stop nzb
      docker_container:
        name: nzbget
        state: stopped
      ignore_errors: yes

    - name: nzb - backup config
      archive:
        path: "{{ pathConfig }}/nzbget"
        dest: "/docker/backup/nzbgetconfig.gz"
        format: gz
        remove: false

    - name: nzb - update image
      shell: docker pull linuxserver/nzbget
      when: update == true

    - name: nzb - remove old container
      shell: docker container rm nzbget

    - name: Nzb - deploy
      docker_container:
        name: nzbget
        image: linuxserver/nzbget:latest
        state: started
        restart_policy: unless-stopped 
        env:
          PUID=0
          PGID=0
          TZ=Europe/London
        ports:
          - 6789:6789
        volumes:
          - "{{ pathConfig }}/nzbget:/config"
          - "{{ pathDownloads }}:/downloads"
        networks:
          - name: "{{ dockerNetwork }}"
            ipv4_address: 172.18.0.12

    - name: radarr - stop
      docker_container:
        name: radarr
        state: stopped
      ignore_errors: yes

    # backup radarrConfig
    - name: radarr - backup config
      archive:
        path: "{{ pathConfig }}/radarr"
        dest: "/docker/backup/radarrconfig.gz"
        format: gz
        remove: false

    - name: radarr - update
      shell: docker pull linuxserver/radarr
      when: update == true

    - name: radarr - remove old container
      shell: docker container rm radarr

    - name: radarr - deploy
      docker_container:
        name: radarr
        image: linuxserver/radarr:latest
        state: started
        restart_policy: unless-stopped
        env:
          PUID=0
          PGID=0
          TZ=Europe/London
          UMASK_SET=022 #optional
        ports:
          - 7878:7878
        volumes:
          - "{{ pathConfig }}/radarr:/config"
          - "{{ pathMedia }}:/movies"
          - "{{ pathDownloads }}:/downloads"
        networks:
          - name : "{{ dockerNetwork }}"
            ipv4_address: 172.18.0.13

    #- name: remove old images
    #  shell: docker image prune --force
