---
- name: mount external nfs disks
  hosts: mediaserver
  vars_files:
    - vars.yml

  tasks:
    - name: make mountpoint
      file:
        path: /docker/dockerconfig
        state: directory

    - name: mount /docker to /docker/dockerconfig
      mount:
        path: 192.168.0.16:/docker
        src: /docker/dockerconfig
        boot: yes
        state: mounted