---
- name: nzbget
  hosts: linux
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: pip docker
      pip:
        name: docker
        executable: pip3
    
    - name: stop nzb
      docker_container:
        name: nzbget
        state: stopped
      ignore_errors: yes

    - name: Make Nzb
      docker_container:
        name: nzbget
        image: linuxserver/nzbget:latest
        state: started
        env:
          PUID=1000
          PGID=1000
          TZ=Europe/London
        ports:
          - 6789:6789
        volumes:
          - "/docker/config/nzbconfig:/config"
          - "/docker/nzbdownloads:/downloads"
        networks:
          - name: "{{ network }}"