---

- name: restore test
  hosts: localhost

  tasks:
    #- name: stop hydra
    #  shell: docker container stop hydra
    #  ignore_errors: true

    #- name: make new vol
    #  docker_volume:
    #    name: hydraConfig
    #    state: absent

    #- name: make new vol
    #  docker_volume:
    #    name: hydraConfig
    #    state: present

    #- name: restore data from tar
    #  shell: docker run --rm -v hydraConfig:/recover -v ~/docker/backup:/backup ubuntu bash -c 'cd /recover && tar xvf /backup/hydraConfig.tar'

    - import_role:
        name: docker_volume_restore
      vars:
        volume_name: hydraConfig
        create_volume: true
        container_name: hydra
        stop_container: true
        backup_folder: '~/docker/backup'
        tar_file: HydraConfig.tar
