---

- name: restore test
  hosts: mediaserver-front
  become: true
  vars:
    name: plex

  tasks:

    #- name: restore data from tar
    #  shell: docker run --rm -v hydraConfig:/recover -v ~/docker/backup:/backup ubuntu bash -c 'cd /recover && tar xvf /backup/hydraConfig.tar'

    - import_role:
        name: docker_volume_management
      vars:
        role_action: restore
        volume_name: "{{ name }}Config"
        create_volume: true
        container_name: "{{ name }}"
        stop_container: true
        backup_folder: '/docker/backup'
        tar_file: "{{ name }}Config.tar"
        recovery_folder: 'Library/Application Support/Plex Media Server/Plug-in Support/Databases/'
