---

- name: restore test
  hosts: mediaserver-back
  become: true

  tasks:

    #- name: restore data from tar
    #  shell: docker run --rm -v hydraConfig:/recover -v ~/docker/backup:/backup ubuntu bash -c 'cd /recover && tar xvf /backup/hydraConfig.tar'

    - import_role:
        name: luther38.docker_volume_management
      vars:
        action: restore
        volume_name: hydraConfig
        create_volume: true
        container_name: hydra
        stop_container: true
        backup_folder: '/docker/backup'
        tar_file: HydraConfig.tar
